### PR TITLE
Adding `PrimeC` homomorphisms

### PR DESCRIPTION
**Pull request by volodeyka**

### CODE REVIEW

**Comment by eupp** [comment]
Have you pushed all changes that we did during the personal meeting?

**Comment by volodeyka** [comment]
> Have you pushed all changes that we did during the personal meeting?

yes

**Review by eupp — APPROVED** [review]
Good job.
Still, CI fails on Coq-dev. I'll post an issue in `bigenough` repo later. 
If you want we can merge it now. Or we can wait until we learn why `bigenough` cause CI to fail on coq-dev.

**Comment by volodeyka** [comment]
> If you want we can merge it now. Or we can wait until we learn why `bigenough` cause CI to fail on coq-dev.

OK, let's wait for a while

**Pull request merged**
